services:
  db:
    image: postgres:14
    env_file:
      - .env
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 15432:5432
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
