default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: test_user
  password: qwerty
  host: localhost
  port: 15432

development:
  <<: *default
  database: dev-database

test:
  <<: *default
  database: test-database

production:
  <<: *default
  database: production-database
